In [44]:
import pandas as pd

In [45]:
!pip install xlrd

Requirement already satisfied: xlrd in C:\Users\yurii\anaconda3\Lib\site-packages (2.0.2)

In [46]:
url = "https://github.com/yurii-slbv/Shark_attack_C/blob/main/GSAF5.xls"

shark_attack = pd.read_excel("GSAF5.xls")

In [47]:
#show columns

shark_attack.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='str')

In [48]:
#drop the columns we don't need

shark_attack = shark_attack.drop(
    columns=[
        'Name', 'Source', 'pdf', 'href formula', 'href',
        'Case Number', 'Case Number.1', 'original order',
        'Unnamed: 21', 'Unnamed: 22'
    ]
)

In [49]:
#drop the rows older than 1975 (left 50 years)
shark_attack = shark_attack[shark_attack['Year'] > 1975]

In [50]:
shark_attack

,Date,Year,Type,Country,State,Location,Activity,Sex,Age,Injury,Fatal Y/N,Time,Species
0,18th September,2026.0,Unprovoked,Australia,Western Australia,Sorrento Beach Perth,Swimming,M,63,Body not recovered,Y,1015hrs,Great White Shark 6m (20ft)
1,16th September,2026.0,Unprovoked,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving,M,?,Injuries to chest shoulder and back,N,1030hrs,Great White Shark
2,14th September,2026.0,Unprovoked,Bahamas,Bimini,Bimini Island,Swimming,F,37,Serious injuries to right ankle,N,1730hrs,Unknown
3,13th September,2026.0,Unprovoked,Australia,Western Australia,Geraldton,Surfing,M,50's,Foot lost in attack,N,0945hrs,Unknown
4,7th September,2026.0,Unprovoked,USA,Hawaii,Honolulu,Surfing,M,24,Scrapes on inside of legs,N,1640hrs,Tiger Shark suspected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,12-Jan-1976,1976.0,Unprovoked,AUSTRALIA,Queensland,Harvey Bay,NaN,F,NaN,Survived,N,NaN,NaN
3996,11-Jan-1976,1976.0,Provoked,SOUTH AFRICA,Western Cape Province,Kalk Bay,Fishing for snoek & yellowtail,NaN,NaN,"Hooked shark leapt onboard & into fish well, w...",N,07h30,"White shark, 3 m [10']"
3997,08-Jan-1976,1976.0,Unprovoked,USA,Florida,"Off Fort Pierce, St Lucie County",Spearfishing / scuba diving,M,25,Puncture wounds to head & neck,N,NaN,6' shark
3998,02-Jan-1976,1976.0,Unprovoked,NEW ZEALAND,North Island,"Te Kaha, East coast",Spearfishing,M,NaN,FATAL,Y,13h00,Bronze whaler shark
3999,1976,1976.0,Unprovoked,USA,Hawaii,"Off Lahaina, Maui",Scuba diving,M,NaN,"FATAL, lost consciousness at depth of 180'. La...",Y,NaN,NaN

In [51]:
# Select only the columns I want to clean
columns_to_clean = ["Country", "State", "Location", "Activity"]

shark_clean = shark_attack[columns_to_clean].copy()

In [52]:
print(shark_clean.isna().sum())

Country       3
State       166
Location    172
Activity    211
dtype: int64

In [53]:
# Remove extra spaces
for column in columns_to_clean:
    shark_clean[column] = shark_clean[column].str.strip()
display(shark_clean.head())

,Country,State,Location,Activity
0,Australia,Western Australia,Sorrento Beach Perth,Swimming
1,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving
2,Bahamas,Bimini,Bimini Island,Swimming
3,Australia,Western Australia,Geraldton,Surfing
4,USA,Hawaii,Honolulu,Surfing

In [54]:
# Replace empty strings with NaN
shark_clean = shark_clean.replace(r"^\s*$", pd.NA, regex=True)

In [55]:
# Standardize capitalization
shark_clean["Country"] = shark_clean["Country"].str.title()
shark_clean["State"] = shark_clean["State"].str.title()
shark_clean["Location"] = shark_clean["Location"].str.title()

In [56]:
# For Activity, remove extra spaces
shark_clean["Activity"] = shark_clean["Activity"].str.strip()

In [57]:
# Check missing values again
print(shark_clean.isna().sum())

Country       3
State       166
Location    172
Activity    212
dtype: int64

In [58]:
# Check cleaned data
display(shark_clean.head(20))

,Country,State,Location,Activity
0,Australia,Western Australia,Sorrento Beach Perth,Swimming
1,Canada,Quebec,Off The Coast Of Perce Le Bilbo Dive Site,Diving
2,Bahamas,Bimini,Bimini Island,Swimming
3,Australia,Western Australia,Geraldton,Surfing
4,Usa,Hawaii,Honolulu,Surfing
5,Usa,Florida,New Smyrna Beach,Surfing
6,Usa,Florida,30 Miles Off Pensacola,Spearfishing
7,Usa,Massachusetts,Norton Point Edgartown Marthas Vinyard,Swimming
8,Usa,Hawaii,"Ala Moana Beach Park, Oahu",Surfing
9,Usa,Florida,Boca Grande (Island In The Keys),Wading on a sandbar
10,Reunion Island,Saint-Gilles-Les-Baines,Outer Reef Roches Noires,Spearfishiong
11,Ireland,Waterford,Ardemore County,Fishing
12,Usa,Maine,Scarborough Beach Park,Operation of Rescue Torpedo
13,Usa,South Carolina,Murrells Inlet Garden City,Swimming
14,Usa,Florida,Daytona Beach Shores Volusia County,Swimming
15,Bahamas,Not Stated,Nort Stated,Snorkeling
16,Fiji,Not Stated,Not Stated,Spearfishing
17,Australia,Queensland,Bundaberg,Hydrofoiling
18,Australia,Tasmania,Coral Point Bruny Island,Spearfishing
19,Usa,New York,Jones Beach State Park Long Island,Swimming

In [59]:
# Select only the columns I want to clean (y = Yurii)
columns_to_clean_y = ['Sex', 'Age', 'Injury']

shark_clean_y = shark_attack[columns_to_clean_y].copy()

shark_clean_y

      Sex   Age                                             Injury
0       M    63                                 Body not recovered
1       M     ?               Injuries to chest shoulder and back
2       F    37                    Serious injuries to right ankle
3       M  50's                                Foot lost in attack
4      M     24                          Scrapes on inside of legs
...   ...   ...                                                ...
3995    F   NaN                                           Survived
3996  NaN   NaN  Hooked shark leapt onboard & into fish well, w...
3997    M    25                     Puncture wounds to head & neck
3998    M   NaN                                              FATAL
3999    M   NaN  FATAL, lost consciousness at depth of 180'. La...

[3998 rows x 3 columns]

In [ ]:
# cleaning "Sex"

shark_clean_y["Sex"] = shark_clean_y["Sex"].str.strip().str.upper()

shark_clean_y["Sex"] = shark_clean_y["Sex"].fillna("Unknown")

shark_clean_y.loc[
    ~shark_clean_y["Sex"].isin(["M", "F"]),
    "Sex"
] = "Unknown"

In [71]:
# checking "Sex"

shark_clean_y["Sex"].value_counts(dropna=False)

Sex
M          3121
F           646
Unknown     231
Name: count, dtype: int64

In [ ]:
# Cleaning "Age". Convert valid ages to numbers and replace unclear/non-numeric values with NaN

shark_clean_y["Age"] = pd.to_numeric(
    shark_clean_y["Age"],
    errors="coerce"
)

In [85]:
# checking "Age"

shark_clean_y["Age"].unique()

array([63., nan, 37., 24., 40., 43., 27., 71., 21., 69., 31., 13., 12.,
       17., 35., 19., 11., 20., 38., 39., 16., 22., 55., 26., 56., 25.,
       61., 14., 54., 48., 57.,  8.,  9.,  7., 85., 18., 66., 42., 45.,
       30., 60., 29., 58., 36., 23., 28., 68., 33., 15., 41., 49., 46.,
       65., 64., 32., 10., 62., 52., 44., 47., 59., 50., 34., 77., 73.,
       67.,  6., 53., 51., 75., 70.,  4., 74.,  3., 82., 72.,  5., 86.,
       84., 87.])

In [ ]:
# Cleanign "Injury". Standardize Injury text for keyword-based categorization

shark_clean_y["Injury_clean"] = (
    shark_clean_y["Injury"]
    .str.strip()
    .str.lower()
)

In [ ]:
# checking key-words to create new injury categories

keywords = [
    "fatal",
    "bite",
    "bitten",
    "wound",
    "puncture",
    "laceration",
    "lost",
    "amput",
    "minor",
    "scratch",
    "abrasion",
    "no injury",
    "uninjured",
    "survived"
]

for word in keywords:
    count = shark_clean_y["Injury_clean"].str.contains(
        word,
        case=False,
        na=False
    ).sum()
    
    print(word, count)

fatal 403
bite 128
bitten 1020
wound 209
puncture 240
laceration 777
lost 8
amput 36
minor 284
scratch 18
abrasion 30
no injury 541
uninjured 2
survived 52

In [101]:
# Categorize injury descriptions based on keywords

def categorize_injury(text):
    if pd.isna(text):
        return "Unknown"

    if any(word in text for word in [
        "no details", "not stated", "unknown", "none to report"
    ]):
        return "Unknown"

    if "fatal" in text:
        return "Fatal"

    elif "no injury" in text or "uninjured" in text:
        return "No injury"

    elif any(word in text for word in [
        "amput", "sever", "lost", "torn off",
        "stripped of flesh", "tissue loss"
    ]):
        return "Severe injury"

    elif any(word in text for word in [
        "minor", "scratch", "abrasion"
    ]):
        return "Minor injury"

    elif any(word in text for word in [
        "bite", "bitten", "wound", "puncture",
        "lacerat", "injur", "gash", "cut"
    ]):
        return "Injury"

    else:
        return "Other"

In [103]:
# making a new column "Injury_Category" (instead of old "Injury")

shark_clean_y["Injury_Category"] = shark_clean_y["Injury_clean"].apply(categorize_injury)

In [ ]:
# Final injury categories

shark_clean_y["Injury_Category"].value_counts(dropna=False)

Injury_Category
Injury           2222
No injury         543
Fatal             402
Minor injury      316
Other             265
Severe injury     205
Unknown            45
Name: count, dtype: int64

In [106]:
# Keep only the final cleaned columns

shark_clean_y = shark_clean_y[
    ["Sex", "Age", "Injury_Category"]
].copy()

In [110]:
# checking the result of my cleaning

shark_clean_y.head(20)

   Sex   Age Injury_Category
0    M  63.0           Other
1    M   NaN          Injury
2    F  37.0          Injury
3    M   NaN   Severe injury
4    M  24.0           Other
5    M   NaN          Injury
6    M  40.0          Injury
7    F   NaN          Injury
8    F   NaN       No injury
9    M  43.0          Injury
10   M   NaN       No injury
11   M  27.0          Injury
12   M  71.0       No injury
13   M   NaN          Injury
14   M  21.0          Injury
15   M  69.0          Injury
16   M   NaN          Injury
17   M   NaN          Injury
18   M  31.0   Severe injury
19   M   NaN          Injury